config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: redirect('/watch'), as: :authenticated_root
  end
  root to: redirect('/welcome')

  #HTML
  get '/:id', to: 'programmes#show', constraints: {id: /\d+/}
  get '/:id/:name', to: 'programmes#show', constraints: {id: /\d+/}
  get '/search', to: 'programmes#search'
  get '/watch', to: 'programmes#watch'
  get '/wait', to: 'programmes#wait'
  get '/ignore', to: 'programmes#ignore'
  get '/welcome', to: 'welcome#index'
  get '/.well-known/acme-challenge/:id' => 'welcome#letsencrypt'

  #JSON
  get '/programme_infos/search', to: 'programme_infos#search'
  get '/programme_infos/show', to: 'programme_infos#show'
  get '/tracked_programmes/show', to: 'tracked_programmes#show'
  get '/tracked_programmes/index', to: 'tracked_programmes#index'
  post 'tracked_programmes/create', to: 'tracked_programmes#create'
  patch 'tracked_programmes/update', to: 'tracked_programmes#update'
  delete 'tracked_programmes/delete', to: 'tracked_programmes#delete'
  put 'watched_episodes/update', to: 'watched_episodes#update'

  as :user do
    get 'login' => 'users/sessions#new', :as => :new_user_session
    post 'login' => 'users/sessions#create', :as => :user_session
    delete 'logout' => 'users/sessions#destroy', :as => :destroy_user_session

    get 'users/cancel' => 'users/registrations#cancel', :as => :cancel_user_registration
    post 'sign_up' => 'users/registrations#create', :as => :user_registration
    get 'sign_up' => 'users/registrations#new', :as => :new_user_registration
    get 'users/edit' => 'users/registrations#edit', :as => :edit_user_registration
    patch 'sign_up' => 'users/registrations#update'
    put 'sign_up' => 'users/registrations#update'
    delete 'sign_up' => 'users/registrations#destroy'
  end

  devise_for :users, {controllers: { sessions: 'users/sessions', passwords: 'users/passwords', registrations: 'users/registrations' }, skip: [:sessions, :registrations]}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    &copy; <%= Time.now.utc.year %> TrackYourTV
  </div>
</footer>

app/views/layouts/_header_logged_in.erb
<nav class="navbar-custom navbar" id="logged-in-navbar">
  <div class="container">
    <div class="navbar-left">
      <button type="button" class="navbar-toggle pull-left collapsed"
              data-toggle="collapse" data-target="#navbar2"
              aria-expanded="false" aria-controls="navbar"
              style="margin-right: 0px;">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'TrackYourTV', "/watch", class: "navbar-brand dissapearing-brand" %>
    </div>
    <div id="navbar1" class="navbar-right navbar-collapse collapse"
          aria-expanded="false" style="height: 1px; margin-right: -15px;">
      <ul class="nav navbar-nav pull-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle hidden-xs header-name-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_user.name.split.first %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu hidden-xs">
            <li>
              <%= link_to 'Account', edit_user_registration_path %>
            </li>
            <li>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <%= react_component('SearchBoxContainer') %>
    <div id="navbar2" class="navbar-collapse collapse"
          aria-expanded="false" style="height: 1px;">
      <ul class="nav navbar-nav">
        <li class="watch-link">
          <a href="/watch"
              class="special-link"
              data-name="watch"
              data-toggle="collapse"
              data-target=".navbar-collapse.in">
            Watch</a>
        </li>
        <li class="wait-link">
          <a href="/wait"
              class="special-link"
              data-name="wait"
              data-toggle="collapse"
              data-target=".navbar-collapse.in">
            Wait</a>
        </li>
        <li class="ignore-link">
          <a href="/ignore"
              class="special-link"
              data-name="ignore"
              data-toggle="collapse"
              data-target=".navbar-collapse.in">
            Ignore</a>
        </li>
        <li class="visible-xs">
          <%= link_to 'Account', edit_user_registration_path %>
        </li>
        <li class="visible-xs">
          <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="header-filler"></div>
<% if !current_page?(edit_user_registration_path) %>
  <p class="alert hidden"><%= notice %><%= alert %></p>
<% else %>
  <% if notice %>
    <div class="alert alert-success alert-custom">
      <div class="container">
        <%= notice %>
      </div>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger alert-custom">
      <div class="container">
        <%= alert %>
      </div>
    </div>
  <% end %>
<% end %>

<script>
$(document).ready(function() {
  $('#logged-in-navbar').css('background-color', 'rgba(38, 38, 38, 1.0)');
  $(window).scroll(function() {
    if ($(this).scrollTop() > 20) {
      $('#logged-in-navbar').css('background-color', 'rgba(38, 38, 38, 0.8)');
    } else {
      $('#logged-in-navbar').css('background-color', 'rgba(38, 38, 38, 1.0)');
    }
  });
  window.onpopstate = function(e) {
    console.log('pop: ' + e.state);
    if (e.state == "watch" || e.state == "wait" || e.state == "ignore") {
      <% if current_page?("/watch") || current_page?("/wait") || current_page?("/ignore") %>
        ProgrammeActions.filterChange(e.state);
      <% else %>
        location.reload();
      <% end %>
    }
  };
  $('.special-link').click(function(e) {
    <% if current_page?("/watch") || current_page?("/wait") || current_page?("/ignore") %>
      if (e.which == 1) {
        e.preventDefault();
        var filter = e.target.getAttribute('data-name');
        history.pushState(filter, null, "/" + filter);
        ProgrammeActions.filterChange(filter);
      }
    <% end %>
  })
});
</script>

app/views/layouts/_header_logged_out.erb
<nav class="navbar-custom navbar" id="logged-out-navbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle pull-left collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'TrackYourTV', root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse"
          aria-expanded="false" style="height: 1px;">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if current_page?(welcome_path) %>
            <a href="javascript:void(0);" onclick="AuthActions.showSignUpModal()" class="sign-up-link" title="Sign Up">
          <% else %>
            <a href="/sign_up" class="sign-up-link" title="Sign Up">
          <% end %>
            Sign Up
          </a>
        </li>
        <li>
          <% if current_page?(welcome_path) %>
            <a href="javascript:void(0);" onclick="AuthActions.showLoginModal()" class="login-link" title="Login">
          <% else %>
            <a href="/login" class="login-link" title="Login">
          <% end %>
            Log In
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="header-filler"></div>
<% if current_page?(welcome_path) %>
  <p class="alert hidden"><%= notice %><%= alert %></p>
<% else %>
  <% if notice %>
    <div class="alert alert-success alert-custom">
      <div class="container">
        <%= notice %>
      </div>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger alert-custom">
      <div class="container">
        <%= alert %>
      </div>
    </div>
  <% end %>
<% end %>

<%= react_component('AuthPickerContainer') %>

<script>
$(document).ready(function() {
  $('#logged-out-navbar').css('background-color', 'rgba(38, 38, 38, 1.0)');
  $(window).scroll(function() {
    if ($(this).scrollTop() > 50) {
      $('#logged-out-navbar').css('background-color', 'rgba(38, 38, 38, 0.8)');
    } else {
      $('#logged-out-navbar').css('background-color', 'rgba(38, 38, 38, 1.0)');
    }
  })
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrackYourTV</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name='viewport' content='width=device-width, initial-scale=1.0' >
    <meta name="turbolinks-cache-control" content="no-cache">
  </head>

  <body>
    <noscript>
      <div style="border: 1px solid; padding: 10px">
        To use this website you'll need to enable JavaScript in your web browser.
      </div>
    </noscript>

    <% if user_signed_in? %>
      <%= render 'layouts/header_logged_in' %>
    <% else %>
      <%= render 'layouts/header_logged_out' %>
    <% end %>

    <% if current_page?(welcome_path) %>
      <%= yield %>
    <% else %>
      <div class="page-filler">
        <%= yield %>
      </div>
    <% end %>
    <%= render 'layouts/footer' %>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-90414836-1', 'auto');
      ga('send', 'pageview');
    </script>
  </body>
</html>